---
- name: Check if EPEL repository is enabled
  when: ansible_distribution_major_version in ['7', '8', '9']
  block:
    - name: Check YUM repos
      command: yum repolist
      changed_when: false
      register: yumrepo
    - name: Abort if EPEL not found
      fail:
        msg: EPEL repository not found (required for dependencies)
      when: "'epel' not in yumrepo.stdout"

- name: Install packages
  yum:
    name:
      - "{{ pulse_filename }}"
    disable_gpg_check: true
  become: true
