---
- name: Include distribution-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family | regex_replace(' ', '_') | lower }}.yml"

- name: Install required dependencies
  ansible.builtin.package:
    name: "{{ pulse_dependencies }}"
  become: true

- name: Include installation tasks
  ansible.builtin.include_tasks: "install_{{ ansible_os_family | regex_replace(' ', '_') | lower }}.yml"

- name: Check running services
  ansible.builtin.service_facts:
  register: running_services
  become: true

- name: Download Chrome Embedded Browser
  ansible.builtin.command: /opt/pulsesecure/bin/setup_cef.sh install
  args:
    creates: /opt/pulsesecure/lib/cefRuntime/Resources/libcef.so
  become: true
