---
- name: Include distribution-specific variables
  include_vars: "{{ ansible_os_family | regex_replace(' ', '_') | lower }}.yml"

- name: Install required dependencies
  package:
    name:
      - tar
      - bzip2
  become: true

- name: Include installation tasks
  include_tasks: "install_{{ ansible_os_family | regex_replace(' ', '_') | lower }}.yml"

- name: Check running services
  service_facts:
  register: running_services

- name: Disable systemd-resolved (not supported by Pulse Secure)
  include_tasks: resolved.yml
  when:
    - running_services['ansible_facts']['services']['systemd-resolved'] is defined
    - running_services['ansible_facts']['services']['systemd-resolved']['state'] == "started"

- name: Download Chrome Embedded Browser
  command: /opt/pulsesecure/bin/setup_cef.sh install
  args:
    creates: /opt/pulsesecure/lib/cefRuntime/Resources/libcef.so
  become: true
