---
- name: Reset resolv.conf
  become: true
  block:
    - name: Remove /etc/resolv.conf (could be a symlink)
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: absent

    - name: Copy last systemd-resolved resolv.conf stub
      ansible.builtin.copy:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: '0644'

    - name: Remove systemd-resolved comments
      ansible.builtin.lineinfile:
        path: /etc/resolv.conf
        regexp: '^# '
        state: absent

    - name: Restart network
      ansible.builtin.systemd:
        name: "{{ pulse_os_network_service }}"
        state: restarted
