---
- name: Disable and mask systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    masked: true
    enabled: false
  become: true
  notify: Reset resolv.conf

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers

- name: Set configuration file options
  ansible.builtin.lineinfile:
    path: "{{ item.file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: true
  become: true
  loop:
    - file: /etc/resolv.conf
      regexp: 'single-request-reopen'
      line: ''
    - file: /etc/nsswitch.conf
      regexp: '^hosts:'
      line: 'hosts: files myhostname resolve dns'
