---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
platforms:
  - name: pulse-debian12
    box: generic/debian12
    cpus: 1
    memory: 2048
    provider_raw_config_args:
      - customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]

  - name: pulse-ubuntu2204
    box: generic/ubuntu2204
    cpus: 1
    memory: 2048
    provider_raw_config_args:
      - customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]

  - name: pulse-almalinux9
    box: almalinux/9
    cpus: 1
    memory: 2048
    provider_raw_config_args:
      - customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]

  - name: pulse-fedora38
    box: generic/fedora38
    cpus: 1
    memory: 2048
    provider_raw_config_args:
      - customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]

  - name: pulse-opensuse_tumbleweed
    box: opensuse/Tumbleweed.x86_64
    cpus: 1
    memory: 2048
    provider_raw_config_args:
      - customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]

provisioner:
  name: ansible
verifier:
  name: testinfra
lint: |
  yamllint .
  ansible-lint
  flake8
