---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
platforms:
  - name: pulse-debian12
    box: debian/bookworm64
    cpus: 2
    memory: 2048
    provider_raw_config_args:
      - customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]

  - name: pulse-ubuntu2404
    box: bento/ubuntu-24.04
    cpus: 2
    memory: 2048
    provider_raw_config_args:
      - customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]

  - name: pulse-almalinux9
    box: almalinux/9
    cpus: 2
    memory: 2048
    provider_raw_config_args:
      - customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]

  - name: pulse-fedora41
    box:  bento/fedora-41
    cpus: 2
    memory: 2048
    provider_raw_config_args:
      - customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]

  - name: pulse-opensuse-leap
    box: opensuse/Leap-15.6.x86_64
    cpus: 2
    memory: 2048
    provider_raw_config_args:
      - customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]

provisioner:
  name: ansible
verifier:
  name: testinfra
lint: |
  yamllint .
  ansible-lint
  flake8
